--create database DB_Retail;
--use DB_Retail;

select * from customer;
select * from prod_cat_info;
select * from transactions;


/****************************DATA PREPARATION AND UNDERSTANDING ***************************************/

--1.What is the total number of rows in each of the 3 tables in the database?
SELECT 'CUSTOMER' , COUNT(*) AS NO_OF_RECORDS FROM [dbo].[Customer]
UNION ALL
SELECT 'PROD_CAT_INFO', COUNT(*) FROM [dbo].[prod_cat_info]
UNION ALL
SELECT 'TRANSACTIONS', COUNT(*) FROM [dbo].[Transactions]

--2)What is the total number of transactions that have a return?

SELECT COUNT(total_amt) AS COUNT_OF_RETURN
FROM TRANSACTIONS
WHERE total_amt < 0;

--3) 
SELECT *, CONVERT(DATE, TRAN_DATE, 105) AS CONV_DATE FROM TRANSACTIONS 

--4)What is the time range of the transaction data available for analysis?
--  Show the output in number of days, months and years simultaneously in different columns.
SELECT 
MIN(TRAN_DATE) AS START__Date ,MAX(TRAN_DATE) AS End_Date,
DATEDIFF(DAY,MIN(tran_date), MAX(tran_date)) AS Diff_Days,
DATEDIFF(MONTH,MIN(tran_date), MAX(tran_date)) AS Diff_MONTH,
DATEDIFF(YEAR,MIN(tran_date), MAX(tran_date)) AS Diff_YEAR
FROM Transactions

--5)Which product category does the sub-category “DIY” belong to?
SELECT PROD_CAT, PROD_SUBCAT
FROM prod_cat_info
WHERE PROD_SUBCAT = 'DIY' ;

/*************************************DATA ANALYSIS ***************************************/
--1)Which channel is most frequently used for transactions?
SELECT TOP 1 STORE_TYPE AS CHANNEL , COUNT(TRANSACTION_ID) AS COUNT1
FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY 2 DESC

--2)What is the count of Male and Female customers in the database?
SELECT GENDER, COUNT(CUSTOMER_ID) AS COUNT 
FROM CUSTOMER
WHERE GENDER = 'M' OR GENDER = 'F'
GROUP BY Gender;

--3)From which city do we have the maximum number of customers and how many?
SELECT TOP 1 CITY_CODE, COUNT(CUSTOMER_ID) CUST_CNT
FROM CUSTOMER
GROUP BY CITY_CODE
ORDER BY 2 DESC

--4)How many sub-categories are there under the Books category?
SELECT PROD_CAT, COUNT(PROD_SUB_CAT_CODE) AS SUB_CATG_COUNT
FROM prod_cat_info
GROUP BY PROD_CAT
HAVING PROD_CAT = 'BOOKS';

--5)What is the maximum quantity of products ever ordered?
SELECT MAX(QTY) AS MAX_QUANTITY FROM TRANSACTIONS;

--6)What is the net total revenue generated in categories Electronics and Books? ASK QUE
SELECT PROD_CAT , ROUND( SUM(TOTAL_AMT) ,2) AS TOT_REVENUE 
FROM TRANSACTIONS T1
INNER JOIN prod_cat_info T2 ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE AND T1.prod_subcat_code = T2.prod_sub_cat_code
GROUP BY PROD_CAT
HAVING PROD_CAT IN ('ELECTRONICS', 'BOOKS') 

--7) How many customers have >10 transactions with us, excluding returns?
SELECT COUNT(*) AS COUNT_CUST FROM (
SELECT cust_id , COUNT(CUST_ID) AS COUNTF 
FROM TRANSACTIONS
WHERE total_amt > 0
GROUP BY cust_id 
HAVING COUNT(CUST_ID) > 10) AS TBL3;

--8)What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
SELECT ROUND (SUM(TOTAL_AMT),2) AS COMBINE_REVENUE 
FROM TRANSACTIONS T1
INNER JOIN prod_cat_info T2 ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE AND T1.prod_subcat_code = T2.prod_sub_cat_code
WHERE STORE_TYPE = 'FLAGSHIP STORE' AND  PROD_CAT IN ('CLOTHING','ELECTRONICS') 

--9) What is the total revenue generated from “Male” customers in “Electronics” category? 
--Output should display total revenue by prod sub-cat.
select PROD_SUBCAT , round(sum(total_amt),2) as Tol_REV from customer
INNER JOIN TRANSACTIONS T1 ON customer_Id = CUST_ID 
INNER JOIN prod_cat_info T2 ON PROD_SUBCAT_CODE = prod_SUB_cat_code AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
WHERE GENDER = 'M' AND PROD_CAT = 'ELECTRONICS'
GROUP BY PROD_SUBCAT

--10)What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?, 
SELECT TOP 5 PROD_SUBCAT, 
ROUND((SUM(TOTAL_AMT)/(SELECT SUM(TOTAL_AMT) FROM TRANSACTIONS))*100,2)  AS PERCENTAGE_OF_SALES, 
(SUM(QTY)/(SELECT SUM(ABS(QTY))FROM TRANSACTIONS))*100 AS PERCENTAGE_OF_RETURN
FROM Transactions T1
INNER JOIN prod_cat_info T2 ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE AND T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE
GROUP BY PROD_SUBCAT
ORDER BY SUM(TOTAL_AMT) DESC

--11) For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in 
--   last 30 days of transactions from max transaction date available in the data?
SELECT SUM(TOTAL_AMT) AS TOT_REV
FROM TRANSACTIONS 
WHERE CUST_ID IN (
SELECT CUSTOMER_ID FROM CUSTOMER
WHERE DATEDIFF(YEAR,DOB,GETDATE()) BETWEEN 25 AND 35) AND
TRAN_DATE >= DATEADD(DAY,-30,(SELECT MAX(TRAN_DATE) FROM TRANSACTIONS));

--12)Which product category has seen the max value of returns in the last 3 months of transactions?
SELECT TOP 1 PROD_CAT , SUM(ABS(QTY)) AS MAX_RETURNS
FROM TRANSACTIONS T1
INNER JOIN prod_cat_info T2 ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE AND T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE
WHERE QTY < 0  AND TRAN_DATE >= DATEADD(MONTH,-3,(SELECT MAX(TRAN_DATE) FROM TRANSACTIONS))
GROUP BY PROD_CAT 
ORDER BY 2 DESC

--13)Which store-type sells the maximum products; by value of sales amount and by quantity sold?
SELECT TOP 1 STORE_TYPE , SUM(TOTAL_AMT) AS TOTAL_AMT, SUM(QTY) AS SUM_QTY
FROM TRANSACTIONS
WHERE TOTAL_AMT > 0 AND QTY > 0
GROUP BY STORE_TYPE
ORDER BY 2 DESC , 3 DESC;

--14)What are the categories for which average revenue is above the overall average
SELECT PROD_CAT, ROUND(AVG(TOTAL_AMT),2) AS AVERAGE FROM TRANSACTIONS T1
INNER JOIN prod_cat_info T2 ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE AND PROD_SUB_CAT_CODE =PROD_SUBCAT_CODE
GROUP BY PROD_CAT
HAVING AVG(TOTAL_AMT)  > (SELECT AVG(TOTAL_AMT) FROM TRANSACTIONS )

--15)Find the average and total revenue by each subcategory for the categories which are among 
--   top 5 categories in terms of quantity sold.
SELECT PROD_SUBCAT, ROUND(AVG(TOTAL_AMT),2) AS AVERAGE , ROUND(SUM(TOTAL_AMT),2) AS TOT_AMT, SUM(QTY) AS QTY
FROM TRANSACTIONS T1
INNER JOIN prod_cat_info T2 ON T1.prod_subcat_code = T2.prod_sub_cat_code and T1.prod_cat_code = T2.prod_cat_code
WHERE QTY > 0
GROUP BY PROD_SUBCAT 
ORDER BY QTY DESC;

